theme = "slick"
icons = "awesome"

[[block]]                                                                          
block = "net"                                                                         
device = "wlp60s0"                                                              
ssid = false                                                                     
ip = true                                                                       
speed_up = true                                                                 
speed_down = true                                                               
graph_up = false
graph_down = true
interval = 5  

[[block]]
block = "uptime"

[[block]]
block = "pacman"
interval = 900

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{Mug}GB/{MTg}GB({Mup}%)"
format_swap = "{SUg}GB/{STg}GB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
